### ISSUE TITLE
Rework Angle API

### ISSUE THREAD

**Issue by brendanzab** [brendanzab/cgmath#251]
These are a super nice idea, but until we have a nice, composable typed units system like F#'s I'm not sure if having a sub-par API is worth it. :(

**Comment by csherratt** [comment]
We could probably do something like how the `time` api works in golang.

```rust
foo(angle * angle::radian());
foo(angle * angle::degree());
```

```rust
pub fn radian<S: BaseFloat>() -> S { 1.0 }
pub fn degree<S: BaseFloat>() -> S { 0.0174533 }
```

So default as radians, if people want to use degrees you can get get some code that looks more or less intuitive how the operation works.

**Comment by kvark** [comment]
I'm against the change. Having `member: Deg<T>` in your struct encodes the important semantics, which would otherwise need to go into either the name, or the comment.

**Comment by csherratt** [comment]
Maybe we can just improve the signatures of the function in that case.

```rust
fn from_angle(theta: Rad<S>) -> Self;
```
Would become
```rust
fn from_angle<A>(theta: A) -> Self where A: Into<Rad<S>>;
```
This way the function itself takes care of most of the conversion noise, reducing the friction of the API.

**Comment by bjz** [comment]
I've done quite a bit of work on the angle API in [v0.7.0](https://github.com/bjz/cgmath/blob/master/CHANGELOG.md#v070---2015-12-23). Still might need some work getting it up to scratch though.
