### ISSUE TITLE
Weird crashes on android/arm because of memory alignment

### ISSUE THREAD

**Issue by ozkriff** [brendanzab/cgmath#375]
See: https://github.com/ozkriff/zoc/issues/197

**Comment by tomaka** [comment]
https://github.com/rust-lang/rust/issues/27060

I'm surprised that cgmath uses `#[repr(packed)]`. It definitely shouldn't.

**Comment by brendanzab** [comment]
We should remove these then! Thanks for the link @tomaka. Should `#[repr(C)]` should still remain though?

**Comment by tomaka** [comment]
I'd say no, but I don't have a strong opinion on that.
If you want to guarantee that the transmutes to fixed-sized arrays work, in my opinion adding tests is enough.

**Comment by ozkriff** [comment]
It fixes the problem. Bump version? :)
