### ISSUE TITLE
`cast` method for Point, Matrix, ...

### ISSUE THREAD

**Issue by LukasKalbertodt** [brendanzab/cgmath#380]
I've been wondering why the [`cast` method](https://docs.rs/cgmath/0.11.0/cgmath/struct.Vector1.html#method.cast) is only implemented for `Vector*` and not for other types such as `Point*` or `Matrix*`. Is there a deeper mathematical truth I'm not understanding or what's the reason?

**Comment by brendanzab** [comment]
Hmm, yo're right, we should add these. Unfortunately a generic trait would require higher kinded types, but we could still implement them on the types directly.
