### ISSUE TITLE
Implement *Assign traits

### ISSUE THREAD

**Issue by porky11** [brendanzab/cgmath#392]
Example:
```
let mut a: Vector3<_> = …;
a += a; //cannot use `+=` on type `cgmath::Vector3<…>`
```
This is because concept AddAssign is not implemented. Can you implement this (and similar conecpts)? (shouldn't be difficult, I think, but I didn't find, where you implement the other concepts (Add, Sub, Mul, etc.)

**Comment by DaseinPhaos** [comment]
Actually, `AddAssign` was implemented for `Vector$N<B>` where `B: BaseNum`, and `$N` minght be 1, 2, 3, 4. The implementation even covers some cover cases with respect to references, which can be quite handy. They are implemented via some verbose `macro_rules`, in case you wonder.
These are all explicitly documented, I don't see why you'd think they are not.
Perhaps you are trying to use it with some `B` that doesn't implement `BaseNum`?

**Comment by brendanzab** [comment]
I'm gonna close this if you are happy! Feel free to reopen this if not.
