### ISSUE TITLE
Get rid of PartialOrd?

### ISSUE THREAD

**Issue by fulara** [brendanzab/cgmath#396]
Is it possible to get rid of PartialOrd?
I think this is the only trait that this lirbary defines & requires on the Num types. All other comes from approx or num-trait crates. 

Since this trait is just a wrapper around std::cmp maybe it could be removed?

I think that would make possible providing custom num types which could be used by this library without actually having to depend on this library. Seems One would only have to depend on num-trait and approx.

**Comment by brendanzab** [comment]
This would require I get rid of `Array::{min, max}`. This is because there is no polymorphic min and max function in common between integers and floats. Is that an acceptable trade-off?
