### ISSUE TITLE
Swizzle Operators

### ISSUE THREAD

**Issue by elrnv** [brendanzab/cgmath#429]
I'm wondering if there is interest in adding swizzle functions like in GLSL/GLM to vector and point (https://www.khronos.org/opengl/wiki/Data_Type_(GLSL)#Swizzling). If so, I have permutations already working in https://github.com/elrnv/cgmath, that I can make a PR for.

**Comment by brendanzab** [comment]
Nice, I like these! Go ahead if you like! Sorry for the late reply btw 😓

**Comment by elrnv** [comment]
Done in #432
