### ISSUE TITLE
Conversion between points and vectors

### ISSUE THREAD

**Issue by janispritzkau** [brendanzab/cgmath#445]
I want to calculate the dot product of `Vector3` and `Point3` but both need to be `Vector3`. Is it possible to convert between vectors and points?

Subtracting points will give a vector but it doesn't seem optimal
```
let vector = point - Point3::origin();
```

**Comment by ocboogie** [comment]
For anyone else that's trying to do this and finds this, like my self, you can you the [`from_vec`](https://docs.rs/cgmath/0.17.0/cgmath/trait.EuclideanSpace.html#tymethod.from_vec) and [`to_vec`](to_vec), which took me way too long to figure out. This might need to be documented better.
