### ISSUE TITLE
`impl From<[T; 3]> for Vector3<T>`

### ISSUE THREAD

**Issue by derekdreery** [brendanzab/cgmath#454]
Is there a reason this isn't implemented. It is for `&[T; 3]` and `&mut [T; 3]`, and `(T, T, T)`, `&(T, T, T)`.....

**Comment by derekdreery** [comment]
My bad

**Comment by brendanzab** [comment]
What problem did you run into with this? Just curious!

**Comment by derekdreery** [comment]
I can't remember now, but it was silly.

**Comment by brendanzab** [comment]
we all do it! 🤣
